env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".ts", ".tsx"] }],
  "import/extensions": [0, "ignorePackages"],
  "no-underscore-dangle": 0,
  "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
  "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
  "class-methods-use-this": 0
}
globals: {
  React: true,
  google: true,
  mount: true,
  mountWithRouter: true,
  shallow: true,
  shallowWithRouter: true,
  context: true,
  expect: true,
  jsdom: true,
  JSX: true,
}
settings:
  import/resolver: {
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      }